---
title: "demo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup}
library(AgroBayes)
```

```{r - runTest - statics networks only}
runTest<-function(nHarvests, nphases, nAreas, nVars, nClass, area, nsample){
  a_list <- list()
  for(i in 1:nsample){
  areas <- testRunDataGen(nHarvests, nphases, nAreas, nVars, nClass)
  areas_raw <- areas[1:(length(areas)/2)]
  areas_dis <- areas[((length(areas)/2)+1):length(areas)]
  
  a_list[[i]] <- testRunNetworks(areas_dis[[area]],area)
  }
  accumulator <- matrix(nrow = dim(a_list[[1]])[1], ncol = nsample, 0)
  
  for(j in 1:dim(a_list[[1]])[1]){
    for(i in 1:nsample){
      accumulator[j,i] <- a_list[[i]][j,1]
    }
  }
  exit <- a_list[[1]]
  
  for(j in 1:dim(a_list[[1]])[1]){
    exit[j,1] <-
    mean(accumulator[j,])
  }
  exit <- round(exit, 2)
  return(exit)
  }

```

```{r - runTest_2 - statics and dynamics networks}
runTest_2<-function(nHarvests, nphases, nAreas, nVars, nClass, area, nsample){
  a_list <- list()
  a_listD <- list()
  for(i in 1:nsample){
  areas <- testRunDataGen(nHarvests, nphases, nAreas, nVars, nClass)
  areas_raw <- areas[1:(length(areas)/2)]
  areas_dis <- areas[((length(areas)/2)+1):length(areas)]
  
  a_list[[i]] <- testRunNetworks(areas_dis[[area]],area)
  a_listD[[i]] <- createDbn(areas_raw[[area]])
  }
  
  accumulator <- matrix(nrow = dim(a_list[[1]])[1], ncol = nsample, 0)
  accumulatorD <- matrix(nrow = 4, ncol = nsample, 0)
  accumulatorDlist <- list( accumulatorD, accumulatorD, 
                            accumulatorD, accumulatorD)
  
  for(i in 1:4){
  for(j in 1:nsample){
    accumulatorDlist[[i]][1,j] = a_listD[[j]]$natPsoho_approx[i]
    accumulatorDlist[[i]][2,j] = a_listD[[j]]$dmmhc_approx[i]
    accumulatorDlist[[i]][3,j] = a_listD[[j]]$natPsoho_exact[i]
    accumulatorDlist[[i]][4,j] = a_listD[[j]]$dmmhc_exact[i]
  }}
  exitD <- a_listD[[1]]
  #RMSE=1, Rsquared=2, MAE=3 Accuracy=4
  for(i in 1:4){
  exitD$natPsoho_approx[i] <- round(mean(accumulatorDlist[[i]][1,]), 3) 
  exitD$dmmhc_approx[i] <- round(mean(accumulatorDlist[[i]][2,]), 3)
  exitD$natPsoho_exact[i] <- round(mean(accumulatorDlist[[i]][3,]), 3)
  exitD$dmmhc_exact[i] <- round(mean(accumulatorDlist[[i]][4,]), 3)
  }
  
  
  for(j in 1:dim(a_list[[1]])[1]){
    for(i in 1:nsample){
      accumulator[j,i] <- a_list[[i]][j,1]
    }
  }
  exit <- a_list[[1]]
  
  for(j in 1:dim(a_list[[1]])[1]){
    exit[j,1] <-
    mean(accumulator[j,])
  }
  exit <- round(exit, 2)
 
  return(list(exit, exitD))
  }
```

```{r datagen}
nHarvests = 200
nphases = 5
nAreas = 6
nVars = 3
nClass = 3


areas <- testRunDataGen(nHarvests, nphases, nAreas, nVars, nClass)
areas_raw <- areas[1:(length(areas)/2)]
areas_dis <- areas[((length(areas)/2)+1):length(areas)]
```

```{r static Bayesian Network}

  nHarvests = 20
  nphases = 5
  nAreas = 6
  nVars = 3
  nClass = 3
  nsample = 1
  
  area1bn <- runTest(nHarvests, nphases, nAreas, nVars, nClass, 1, nsample)
  area2bn <- runTest(nHarvests, nphases, nAreas, nVars, nClass, 2, nsample)
  area3bn <- runTest(nHarvests, nphases, nAreas, nVars, nClass, 3, nsample)
  area4bn <- runTest(nHarvests, nphases, nAreas, nVars, nClass, 4, nsample)
  area5bn <- runTest(nHarvests, nphases, nAreas, nVars, nClass, 5, nsample)
  area6bn <- runTest(nHarvests, nphases, nAreas, nVars, nClass, 6, nsample)

# to use this functionality, uncomment the 
# excerpt below and inform the path to the outputs in the file variables
  
# #a1
#   file = "path_to_where_save_the_outputs"
#   geraGraph(area1bn, file, "Area 1")
#   file2 = "path_to_where_save_the_outputs"
#   write.csv(area1bn, file2)
#   
# #a2
#   file = "path_to_where_save_the_outputs"
#   geraGraph(area2bn, file,  "Area 2")
#   file2 = "path_to_where_save_the_outputs"
#   write.csv(area2bn, file2)
#   
# #a3
#   file = "path_to_where_save_the_outputs"
#   geraGraph(area3bn, file,  "Area 3")
#   file2 = "path_to_where_save_the_outputs"
#   write.csv(area3bn, file2)
#   
# #a4
#   file = "path_to_where_save_the_outputs"
#   geraGraph(area4bn, file, "Area 4")
#   file2 = "path_to_where_save_the_outputs"
#   write.csv(area4bn, file2)
#   
# #a5
#   file = "path_to_where_save_the_outputs"
#   geraGraph(area5bn, file, "Area 5")
#   file2 = "path_to_where_save_the_outputs"
#   write.csv(area5bn, file2)
#   
# #a6
#   file = "path_to_where_save_the_outputs"
#   geraGraph(area6bn, file,  "Area 6")
#   file2 = "path_to_where_save_the_outputs"
#   write.csv(area6bn, file2)
```

```{r test 100 e 200}
  nHarvests = 200
  nphases = 5
  nAreas = 6
  nVars = 3
  nClass = 3
  area = 1
  nsample = 1
  
area1 <-runTest_2(nHarvests, nphases, nAreas, nVars, nClass, 1, nsample)
area2 <-runTest_2(nHarvests, nphases, nAreas, nVars, nClass, 2, nsample)
area3 <-runTest_2(nHarvests, nphases, nAreas, nVars, nClass, 3, nsample)
area4 <-runTest_2(nHarvests, nphases, nAreas, nVars, nClass, 4, nsample)
area5 <-runTest_2(nHarvests, nphases, nAreas, nVars, nClass, 5, nsample)
area6 <-runTest_2(nHarvests, nphases, nAreas, nVars, nClass, 6, nsample)


area1bn <- area1[[1]]
area2bn <- area2[[1]]
area3bn <- area3[[1]]
area4bn <- area4[[1]]
area5bn <- area5[[1]]
area6bn <- area6[[1]]

area1Dbn <- area1[[2]]
area2Dbn <- area2[[2]]
area3Dbn <- area3[[2]]
area4Dbn <- area4[[2]]
area5Dbn <- area5[[2]]
area6Dbn <- area6[[2]]


planilhao = data.frame(rbind(area1Dbn,
                                area2Dbn,
                                area3Dbn,
                                area4Dbn,
                                area5Dbn,
                                area6Dbn
                                ))

RMSE <- data.frame()
i=1
for(a in 1:6){
  RMSE<-data.frame(rbind(RMSE, planilhao[i,]))
  i=i+4
}

Rsquared <-data.frame()
i=2
for(a in 1:6){
  Rsquared<-data.frame(rbind(Rsquared, planilhao[i,]))
  i=i+4
}

MAE <-data.frame()
i=3
for(a in 1:6){
  MAE<-data.frame(rbind(MAE, planilhao[i,]))
  i=i+4
}

Accuracy <-data.frame()
i=4
for(a in 1:6){
  Accuracy<-data.frame(rbind(Accuracy, planilhao[i,]))
  i=i+4
}

# to use this functionality, uncomment the 
# excerpt below and inform the path to the outputs in the file variables

# file3 = "path_to_where_save_the_outputs"
# write.csv(MAE, file3)
# file3 = "path_to_where_save_the_outputs"
# write.csv(Accuracy, file3)
# file3 = "path_to_where_save_the_outputs"
# write.csv(RMSE, file3)
# file3 = "path_to_where_save_the_outputs"
# write.csv(Rsquared, file3)
# 
# # a1
#   file = "path_to_where_save_the_outputs"
#   geraGraph(area1bn, file, "Area 1")
#   file2 = "path_to_where_save_the_outputs"
#   write.csv(area1bn, file2)
#   
# #a2
#   file = "path_to_where_save_the_outputs"
#   geraGraph(area2bn, file,  "Area 2")
#   file2 = "path_to_where_save_the_outputs"
#   write.csv(area2bn, file2)
#   
# #a3
#   file = "path_to_where_save_the_outputs"
#   geraGraph(area3bn, file,  "Area 3")
#   file2 = "path_to_where_save_the_outputs"
#   write.csv(area3bn, file2)
#   
# #a4
#   file = "path_to_where_save_the_outputs"
#   geraGraph(area4bn, file, "Area 4")
#   file2 = "path_to_where_save_the_outputs"
#   write.csv(area4bn, file2)
#   
# #a5
#   file = "path_to_where_save_the_outputs"
#   geraGraph(area5bn, file, "Area 5")
#   file2 = "path_to_where_save_the_outputs"
#   write.csv(area5bn, file2)
#   
# #a6
#   file = "path_to_where_save_the_outputs"
#   geraGraph(area6bn, file,  "Area 6")
#   file2 = "path_to_where_save_the_outputs"
#   write.csv(area6bn, file2)

```



